### ISSUE TITLE
Tests hang when running with --unstable (Oak 7.3, SuperOak 4.2, Deno 1.9.2)

### ISSUE THREAD

**Issue by avihavai** [asos-craigmorten/superoak#22] opened 2021-04-29 09:20 UTC
# Issue

Hi! When running Deno superoak tests with `--unstable` flag in recent Deno / Oak -versions, the tests get stuck. 

Setup:

- Deno Version: 1.9.0+ (earlier versions, e.g. 1.8.3, not affected)
- Oak Version: 7.0.0+ (earlier versions, e.g. v6.5.0, not affected)
- SuperOak Version: 4.0.0+

## Details

Example code: 

```js
import { Application } from "https://deno.land/x/oak@v7.3.0/mod.ts";
import { superoak } from "https://deno.land/x/superoak@4.2.0/mod.ts";

const app = new Application();

const greet = (context) => {
  context.response.body = "Hello world!";
};

app.use(greet);

Deno.test("Response is 'Hello world!'", async () => {
  const response = await superoak(app);
  await response
    .get("/")
    .expect("Hello world!");
});
```

When running the tests with `deno test --allow-net --unstable app.js`, the tests get stuck. However, with `deno test --allow-net app.js`, the tests can be successfully run. This might have something to do with the native HTTP server enabled in oak when using the `--unstable`-flag, but have not looked into this in detail. Oak can be normally used with the `--unstable` flag though.

**Comment by cmorten** [comment] 2021-04-29 09:33
Hi @avihavai 👋 

Thanks for raising this - I suspect, as you allude to, this is due to Oak now switching to native HTTP bindings under the hood when `—unstable` is provided for one of the recent `^1.9.0` Deno versions.

I’ve got a feeling a simple feature detection + adjustment to call signature should do it, but needs some more investigation. Until then will say that we support the “old” Oak server but not the new unstable version just yet ( though your reasons for using unstable may well be for other libs in your server which this doesn’t then help with 😅 ).

If you’re up for investigating then really appreciate contributions, otherwise may start looking at it today / tomorrow, workload permitting!

**Comment by cmorten** [comment] 2021-04-29 09:49
Hmm, just given a quick spike and my issue atm seems to be that the abort controller doesn't seem to closing the server as expected - will continue to investigate!

**Comment by avihavai** [comment] 2021-04-29 09:50
Hi and thanks! :). Out of curiosity, I took a quick peek at SuperDeno + Opine, and the `--unstable`+hang -issue does not appear there. Unfortunately, I'm quite packed at work at the moment and can't promise to look into this in the near future. Regarding the versions, I'm forced to use `--unstable` due to other libraries at the moment -- but, can jump back to an older Oak-version for now. Thanks for the effort with the library!

**Comment by cmorten** [comment] 2021-04-29 09:57
I think I've found a bug in Oak - the `closeServer` example doesn't work as intended when using the native bindings, raising an issue there and might take a look at fixing that 🤞

**Comment by avihavai** [comment] 2021-04-29 09:58
Nice! Looking forward to a fix! Great work!

**Comment by cmorten** [comment] 2021-04-29 10:08
See https://github.com/oakserver/oak/issues/304

**Comment by cmorten** [comment] 2021-05-02 07:44
Issue on Oak was closed by https://github.com/oakserver/oak/commit/a7e053cad739b6778683353b137c4379849df1e0. Awaiting a new version to be released so we can test to confirm everything is working.

**Comment by cmorten** [comment] 2021-05-08 09:48
`oak@7.4.0` has been released but appears to have a similar ( well subtly different ) error which prevents us from using superoak as desired.

See https://github.com/oakserver/oak/issues/314

**Comment by cmorten** [comment] 2021-05-08 13:02
Suspecting https://github.com/denoland/deno/issues/10508 may be related to some of the issues find when try to work around Oak’s current state

**Comment by jsjoeio** [comment] 2021-06-04 17:39
Looks like https://github.com/denoland/deno/issues/10508#issuecomment-854251753 has been fixed and closed!

**Comment by asos-craigmorten** [comment] 2021-08-19 16:19
Raised https://github.com/oakserver/oak/pull/389 which think should resolve this issue.

**Comment by cmorten** [comment] 2021-08-23 07:05
Merged 🎉 expect to be fixed next Oak release 🙃

**Comment by asos-craigmorten** [comment] 2021-09-29 08:44
Fixed in latest version upstream https://deno.land/x/oak@v9.0.1

**Closed as completed by asos-craigmorten** 2021-09-29 08:44 UTC
Labels: bug
